sudo: required
services:
  - docker
before_install:
  - docker build -t muzammil76/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -it muzammil76/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "first_app"
  env: "FirstApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-663810187498"
  bucket_path: "first_app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
